pipeline:
  restore_cache:
    image: plugins/s3-cache
    pull: true
    endpoint: https://s3.amazonaws.com
    root: /drone-cache-fusionapp-useast
    restore: true
    mount:
      - /drone/stack
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event:
        - push
        - pull_request
        - tag
  build:
    image: fusionapp/debian-stack
    pull: true
    environment:
      - STACK_ROOT=/drone/stack
    commands:
      - stack setup
      - stack build --test
      - mkdir -p $PWD/dist
      - stack --local-bin-path $PWD/dist build --copy-bins
    when:
      event:
        - push
        - pull_request
        - tag
  rebuild_cache:
    image: plugins/s3-cache
    pull: true
    endpoint: https://s3.amazonaws.com
    root: /drone-cache-fusionapp-useast
    rebuild: true
    mount:
      - /drone/stack
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event: push
      branch:
        - master
  flush_cache:
    image: plugins/s3-cache
    pull: true
    endpoint: https://s3.amazonaws.com
    root: /drone-cache-fusionapp-useast
    flush: true
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event: push
      branch:
        - master
  publish:
    image: plugins/ecr
    region: eu-west-1
    registry: 801493518741.dkr.ecr.eu-west-1.amazonaws.com
    repo: 801493518741.dkr.ecr.eu-west-1.amazonaws.com/drone-scheduler
    tags:
      - ${DRONE_BRANCH}
      - git-${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master
    secrets:
      - ecr_access_key
      - ecr_secret_key
  deploy:
    image: peloton/drone-rancher
    url: https://rancher.fusionapp.com
    service: Drone7/drone-scheduler
    docker_image: 801493518741.dkr.ecr.eu-west-1.amazonaws.com/drone-scheduler:git-${DRONE_COMMIT_SHA}
    start_first: false
    confirm: true
    timeout: 240
    when:
      event: push
      branch: master
    secrets:
      - rancher_access_key
      - rancher_secret_key
  slack:
    image: plugins/slack
    secrets:
      - slack_webhook
    when:
      status:
        - success
        - failure
branches:
  - master
